stages:
  - build
  - test
  - deploy

# Docker Runner - Cloning upstream repository
job_makepkg:
  stage: build
  script:
    - /bin/sh -c "cd /home/guest && git clone https://aur.archlinux.org/package-query.git && cd package-query && makepkg -sf"
  tags:
    - arch
    - docker

# Docker Runner - Building your own PKGFILE
job_makepkg:
  stage: build
  script:
    - /bin/sh -c "makepkg -s --noconfirm --noprogressbar"
  tags:
    - arch
    - docker

# Shell Runner - Pulling and running a docker image (upstream repositoty or own PKGBUILD)
job_docker_build:
  stage: build
  script:
    - docker pull rafaelsoares/archlinux:2016-04-09-devel
    - docker run rafaelsoares/archlinux:2016-04-09-devel /bin/sh -c "cd /home/guest && git clone https://aur.archlinux.org/package-query.git && cd package-query && makepkg -sf"
  tags:
    - arch
    - shell

# Shell Runner - Building a docker image using Dockerfile (upstream repository or own PKGBUILD)
job_docker_build:
  stage: build
  script:
    - docker build -t package-query .
  tags:
    - arch
    - shell

# Shell Runner - Building on Arch Linux Hosts
job_docker_build:
  stage: build
  script:
    - makepkg -s --noconfirm --noprogressbar
  tags:
    - arch
    - shell
