language: C

services:
  - docker

before_install:
- docker pull rafaelsoares/archlinux-devel

script:
- docker run rafaelsoares/archlinux-devel /bin/sh -c "cd /home/guest && git clone https://aur.archlinux.org/package-query.git && cd package-query && makepkg -sf"
