language: C

services:
  - docker

before_install:
- docker pull rafaelsoares/archlinux:2016-04-09-devel

script:
- docker run rafaelsoares/archlinux:2016-04-09-devel /bin/sh -c "cd /home/guest && git clone https://github.com/rafaelsoaresbr/package-query.git && cd package-query && makepkg -s"
